---
title: "Quantitative Finance  Algorithmic Trading in Python"
---

# Section 1 - Introduction
- installing Python
- why to use Python programming language
- the problem with financial models and historical data
  
# Section 2 - Stock Market Basics

## Present value and future value of money

Key Concepts

- Time Value of Money: Money today is worth more than money in the future due to its potential earning capacity and inflation.
- Present Value (PV): The current value of a future sum of money discounted at a specific interest rate.
- Future Value (FV): The value of a current asset at a future date based on an assumed rate of growth.
  
Investment Scenarios

- Treasury Bills
- Corporate Bonds
- Stocks
  
Investments carry risks, leading to a premium (interest) received.

```{python}
from math import exp

def future_discrete_value(x: float, r: float, n: int):
    return x*(1 + r)**n

def present_discrete_value(x: float, r: float, n: int):
    return x*(1 + r)**-n

def future_continuous_value(x: float, r: float, t: int):
    return x*exp(r*t)

def present_continuous_value(x: float, r: float, t: int):
    return x*exp(-r*t)
```

```{python}
# Value of investment in dollars
x = 100
# Define the interest rate (r)
r  = 0.05
# Duration (years)
n = 5

print("Future values (discrete model) of x: %s" % future_discrete_value(x,r,n))
print("Present values (discrete model) of x: %s" % present_discrete_value(x,r,n))
print("Future values (continuous model) of x: %s" % future_continuous_value(x,r,n))
print("Present values (continuous model) of x: %s" % present_continuous_value(x,r,n))
```

### Calculations
#### Discrete Model

**Future Value**
$$FV = PV \cdot (1+r)^n$$

**Future Value**
$$PV = \frac{FV}{(1+r)^n}$$

- $FV$ = Future Value
- $PV$ = Present Value
- $r$ = Interest Rate
- $n$ = Duration (years)

#### Continuous Model
Using differential equations, the future value in continuous time is modeled by an exponential function.

**Future Value**

$$FV = PV \cdot e^{rt}$$


**Present Value**

$$PV = \frac{FV}{e^{rt}}$$

- $FV$ = Future Value
- $PV$ = Present Value
- $e$ = Base of the natural logarithm
- $r$ = Interest Rate
- $t$ = Duration (years)


# Section 3 - Bond Theory and Implementation

A bond is a debt investment in which an investor loans money to an entity (a company or a government) for a defined period of time, with variable or fixed interest rates. Bonds are usually called fixed income securities.

When a company needs to raise money to finance new projects, they may issue bonds directly to investors instead of obtaining loans from the bank. There are three options for raising capital: bank loans, issuing bonds, and going public (selling stocks).

There are two main types of bonds: zero coupon bonds and coupon bonds.

1. **Zero Coupon Bonds**:
   - Have three important parameters: principal amount, interest rate, and time to maturity.
   - The principal amount is paid to the investor after the specified period.
   - The current value of the bond is calculated by discounting the principal amount using the market interest rate.

2. **Coupon Bonds**:
   - Have a principal amount, a coupon rate (a nominal percentage of the principal paid annually), and time to maturity.
   - Annual coupon payments are made to the investor, and the principal is paid at the end of the period.
   - The bond's value is calculated by discounting both the annual coupon payments and the principal amount using the market interest rate
$$\sum_{i=1}^n \frac{c}{(1+r)^i} + \frac{x}{(1+r)^i}$$
 

$$\frac{c}{r} \left[ 1 + \frac{1}{(1+r)^n} \right] + \frac{x}{(1+r)^i}$$

For both types of bonds, the present value is calculated by discounting future cash flows using the market interest rate, not the bond's interest rate.

In the upcoming lectures, we will discuss interesting features of bonds in more detail.
## Yields and Yield to Maturity

### Yield

A yield is a figure that shows the return you get on a given bond. It is calculated using the following formula:

$$
\text{Yield} = \frac{\text{Annual Coupon Payment}}{\text{Price of the Bond}}
$$

For example, if the annual coupon payment is $100 and the price of the bond is $1167, the yield is:

$$
\text{Yield} = \frac{100}{1167}
$$

### Yield to Maturity (YTM)

The yield to maturity (YTM) of a bond is the internal rate of return earned by an investor who buys the bond at the current market price and holds it until maturity. It is the interest rate that makes the present value of future cash flows from the bond equal to the current price of the bond.

The equation to calculate YTM is:

$$
\text{Bond Price} = \sum_{t=1}^{T} \frac{\text{Coupon Payment}}{(1+Y)^t} + \frac{\text{Principal}}{(1+Y)^T}
$$

- \( \text{Bond Price} \): Current price of the bond
- \( t \): Time period
- \( T \): Maturity period
- \( Y \): Yield to maturity
- \( \text{Coupon Payment} \): Periodic payment made by the bond
- \( \text{Principal} \): Face value of the bond

### Discounting with Continuous Model

In the continuous model, we use exponential functions for discounting. The present value (PV) of the bond is calculated as follows:

$$
PV = \sum_{t=1}^{T} \text{Coupon Payment} \cdot e^{-Yt} + \text{Principal} \cdot e^{-YT}
$$

- \( e \): Base of the natural logarithm
- \( Y \): Yield to maturity
- \( t \): Time period
- \( T \): Maturity period

### Yield Curves

A yield curve is a graph showing the relationship between the yield and the time to maturity for bonds. The yield curve typically has the following shape:

- **Vertical Axis**: Yield
- **Horizontal Axis**: Time to maturity

The yield curve usually slopes upwards, indicating that longer-term bonds offer higher yields due to increased risk. Investors expect more yield in return for loaning their money for a longer period of time. This is because long-term bonds pose more risk, such as the possibility of more attractive investments arising or negative effects impacting the bonds.

In finance, higher risk is typically rewarded with higher yield. Therefore, bonds with longer times to maturity generally have higher yields.


# Section 4 - Modern Portfolio Theory (Markowitz Model)

- what is diverzification in finance?
- mean and variance
- efficient frontier and the Sharpe ratio
- capital allocation line (CAL)

# Section 5 - Capital Asset Pricing Model (CAPM)

- systematic and unsystematic risks
- beta and alpha parameters
- linear regression and market risk
- why market risk is the only relevant risk?

# Section 6 - Derivatives Basics

- derivatives basics
- options (put and call options)
- forward and future contracts
- credit default swaps (CDS)
- interest rate swaps


# Section 7 - Random Behavior in Finance

- random behavior
- Wiener processes
- stochastic calculus and Ito's lemma
- brownian motion theory and implementation

# Section 8 - Black-Scholes Model

- Black-Scholes model theory and implementation
- Monte-Carlo simulations for option pricing
- the greeks

# Section 9 - Value-at-Risk (VaR)

- what is value at risk (VaR)
- Monte-Carlo simulation to calculate risks

# Section 10 - Collateralized Debt Obligation (CDO)

- what are CDOs?
- the financial crisis in 2008

# Section 11 - Interest Rate Models

- mean reverting stochastic processes
- the Ornstein-Uhlenbeck process
- the Vasicek model
- using Monte-Carlo simulation to price bonds

# Section 12 - Value Investing

- long term investing
- efficient market hypothesis